#!/bin/bash
java -jar transfer/lib/transfer.jar output/../../STPDataType.cs transfer/xml/EntityModel.xml transfer/xsl/DataType_template_cs.xsl
java -jar transfer/lib/transfer.jar output/../../STPDataStruct.cs transfer/xml/EntityModel.xml transfer/xsl/TFDataStruct_template_cs.xsl
java -jar transfer/lib/transfer.jar output/../../STPAllEnumInfo.cs transfer/xml/EntityModel.xml transfer/xsl/DataTypeToEnum_template_cs.xsl